### PR TITLE
Mention acl:accessTo and acl:default object URIs should match resource URI exactly

### LINKED ISSUE #49: say something about trailing slashes
In https://www.w3.org/TR/ldp-bp/#include-a-trailing-slash-in-container-uris it's recommended to refer to a container with a trailing slash, but i think it can be expected of a server to add that trailing slash if it's missing?
For instance I I write:
```turtle
<#owner> acl:accessTo <https://mypod.com/foo> .
```
in https://mypod.com/foo/.acl then the server should interpret that as
```turtle
<#owner> acl:accessTo <https://mypod.com/foo/> .
```

### PR DESCRIPTION
**Pull request by michielbdejong**
Fixes #49

### CODE REVIEW

**Comment by csarven** [comment]
Specs ought to develop independently, and should not be based on a particular implementation or convention. That goes for WAC not having knowledge or dependency on LDP or expect that WAC should follow a specific URI Template.

**Comment by michielbdejong** [comment]
Right, that makes sense, thanks! Updated.

**Comment by michielbdejong** [comment]
Thanks! Can someone merge it (or give me permissions to do so)?

**Comment by michielbdejong** [comment]
Thanks!

**Pull request merged**
