### PR TITLE
remove acl:GroupListing

### LINKED ISSUE #16: definition and purpose of acl:GroupListing
https://github.com/solid/web-access-control-spec#groups-of-agents

Class `acl:GroupListing` doesn't seem to have any purpose, all groups have WebID (IRI denoting the instance of `vcard:Group`) and giving additional class to `foaf:Document` which has as its topic / describes one or more instances of `vcard:Group` doesn't seem to have any advantages.

> The object of an agentGroup statement is a link to a Group Listing document.

It seems that WebID of a group gets used

```
    acl:agentGroup <https://alice.example.com/work-groups#Accounting>;
    acl:agentGroup <https://alice.example.com/work-groups#Management>.
```

and not the URL of the document `<https://alice.example.com/work-groups>`

### PR DESCRIPTION
**Pull request by elf-pavlik**
closes #16

### CODE REVIEW

**Comment by elf-pavlik** [comment]
:wave:

**Comment by elf-pavlik** [comment]
This PR boils down to a tiny cleanup, still over a month later no response from maintainers?

**Comment by elf-pavlik** [comment]
I hope someone could finally review it, merge and close #16 (BTW @timbl already agreed in that issue with my suggestion materialized in this PR)

**Comment by elf-pavlik** [comment]
ping @kjetilk

**Comment by elf-pavlik** [comment]
This morning during the group call no one raised any objections.

**Comment by kjetilk** [comment]
Allright, sounds good! :-)

**Pull request merged**
